// app/actions/jobs.ts
"use server";

import { createClient } from "@/lib/supabase";

export async function createJob(formData: FormData) {
  const supabase = createClient();

  const jobData = {
    title: formData.get("title"),
    company: formData.get("company"),
    company_email: formData.get("email"),
    description: formData.get("description"),
    location: formData.get("job_type"),
    salary_range: formData.get("salary_range"),
    // management_token is auto-generated by the database
  };

  const { data, error } = await supabase.from("job_listings").insert(jobData).select().single();

  if (error) throw error;

  return {
    jobId: data.id,
    managementToken: data.management_token,
  };
}

export async function getJobByToken(token: string) {
  const supabase = createClient();

  const { data, error } = await supabase.from("job_listings").select("*").eq("management_token", token).single();

  if (error) throw error;
  return data;
}
